version: '3'

services:
  back-end:
    build: ./back-end
    ports:
      - 3000:3000

  front-end:
    build: ./front-end
    ports:
      - 80:80
    links:
      - back-end
    depends_on:
      - back-end